version 0.3.4

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -1,29 +1,21 @@
 #!/bin/bash
 
-#############
-# CONSTANTS #
-#############
+# ----- CONSTANTS ----- #
 start_spaceify="# Added by Spaceify"
 end_spaceify="# Added by Spaceify ends"
 comm_out_spaceify="# Commented out by Spaceify: "
 
-############
-# DATABASE #
-############
-. /var/lib/spaceify/data/scripts/database.sh
-
-#######################
-# DEBCONF - GET INPUT #
-#######################
+# ----- DEBCONF - GET INPUT ----- #
 . /var/lib/spaceify/data/scripts/input.sh
 
 eth=$(</var/lib/spaceify/data/interfaces/ethernet)
 wlan=$(</var/lib/spaceify/data/interfaces/wlan)
 is_internal=$(</var/lib/spaceify/data/interfaces/is_internal)
 
-################################
-# MODIFY CONFIGURATION SCRIPTS #
-################################
+# ----- DATABASE ----- #
+. /var/lib/spaceify/data/scripts/database.sh
+
+# ---------- MODIFY CONFIGURATION SCRIPTS ---------- #
 
 # ----- /etc/network/interfaces - give ip to wlan0 (or what adapter names user selected) ----- #
 
@@ -181,9 +173,7 @@ ln -s /etc/init/spaceifyappman.conf /etc/init.d/spaceifyappman > /dev/null 2>&1 
 sed -i "s/interface1/${eth}/g" /etc/init/spaceifydns.conf									# Replace the real network interface names to the dns service script
 sed -i "s/interface2/${wlan}/g" /etc/init/spaceifydns.conf
 
-####################
-# EXECUTE COMMANDS #
-####################
+# ---------- EXECUTE COMMANDS ---------- #
 
 # ----- Spaceify's DNS server must be on and other DNS mechanisms off ----- #
 	# -- remove Spaceify's previous entries -- #
@@ -233,7 +223,8 @@ fi
 
 	# -- interface must be up -- #
 x=300
-printf "\nWaiting for maximum of $x seconds for the network interface $eth to come up.\n"
+printf "\n\e[4mWaiting for maximum of $x seconds for the network interface $eth to come up\e[0m\n\n"
+
 ping -c 1 -W 1 8.8.8.8 > /dev/null 2>&1
 while [ $? -ne 0 ]; do
 	let x-=1
@@ -248,11 +239,11 @@ while [ $? -ne 0 ]; do
 done
 
 if [[ $x -eq 0 ]]; then
-	. /var/lib/spaceify/data/scripts/cleanup_installation.sh "remove"
-	printf "\nAborting the installation because getting the interface up failed. Run 'apt-get --purge remove Spaceify' to remove incomplete installation.\n\n"
+	. /var/lib/spaceify/data/scripts/cleanup_installation.sh "purge"
+	printf "Aborting the installation because getting the interface up failed. Run 'apt-get purge spaceify' to remove incomplete installation.\n"
 	exit 1
 else
-	printf "\nThe interface is up. Continuing the installation.\n\n"
+	printf "The interface is up. Continuing the installation.\n"
 fi
 
 	# -- start the Spaceify DNS server -- #
@@ -260,7 +251,7 @@ service spaceifydns restart > /dev/null 2>&1 || true
 
 # ----- Add custom iptables chains for Spaceify ----- #
 
-# To avoid duplicates delete existing rules
+	# -- To avoid duplicates, delete existing rules -- #
 iptables -t mangle -D PREROUTING -j Spaceify-mangle > /dev/null 2>&1 || true
 iptables -t mangle -F Spaceify-mangle > /dev/null 2>&1 || true
 iptables -t mangle -X Spaceify-mangle > /dev/null 2>&1 || true
@@ -282,7 +273,7 @@ iptables -t nat -X Spaceify-HTTPS-Nat-Masq > /dev/null 2>&1 || true
 iptables -t nat -F Spaceify-HTTPS-Nat-Redir > /dev/null 2>&1 || true
 iptables -t nat -X Spaceify-HTTPS-Nat-Redir > /dev/null 2>&1 || true
 
-# Mangle chain
+	# -- Mangle chain -- #
 #iptables -t mangle -N Spaceify-mangle
 #iptables -t mangle -A PREROUTING -j Spaceify-mangle
 #iptables -t mangle -A Spaceify-mangle -i docker0 -j RETURN
@@ -291,7 +282,7 @@ iptables -t nat -X Spaceify-HTTPS-Nat-Redir > /dev/null 2>&1 || true
 #iptables -t nat -A PREROUTING -m mark --mark 99 -p tcp --dport 443 -j DNAT --to-destination 10.0.0.1
 #iptables -t filter -A FORWARD -m mark --mark 99 -j DROP
 
-# HTTP filter chain, NAT chain and redirect chain
+	# -- HTTP filter chain, NAT chain and redirect chain -- #
 iptables -t nat -N Spaceify-HTTP-Nat-Redir
 iptables -t nat -A PREROUTING -j Spaceify-HTTP-Nat-Redir
 iptables -t nat -A Spaceify-HTTP-Nat-Redir -d 10.0.0.1/32 -j ACCEPT
@@ -301,7 +292,7 @@ iptables -t nat -N Spaceify-HTTP-Nat-Masq
 iptables -t nat -A POSTROUTING -j Spaceify-HTTP-Nat-Masq
 iptables -t nat -A Spaceify-HTTP-Nat-Masq -o "${eth}" -j MASQUERADE 
 
-# HTTPS filter chain, NAT chain and redirect chain
+	# -- HTTPS filter chain, NAT chain and redirect chain -- #
 iptables -t nat -N Spaceify-HTTPS-Nat-Redir
 iptables -t nat -A PREROUTING -j Spaceify-HTTPS-Nat-Redir
 iptables -t nat -A Spaceify-HTTPS-Nat-Redir -d 10.0.0.1/32 -j ACCEPT
@@ -317,7 +308,7 @@ echo 1 > /proc/sys/net/ipv4/ip_forward
 
 # ----- Certificates and keys ----- #
 
-# Copy certificates and keys to Spaceify's folders from Squid's folders
+	# -- Copy certificates and keys to Spaceify's folders from Squid's folders -- #
 mkdir /var/lib/spaceify/code/www/ > /dev/null 2>&1 || true
 mkdir /var/lib/spaceify/data/tls/ > /dev/null 2>&1 || true
 cp /etc/squid3/certs/spaceifyCA/spaceify.crt /var/lib/spaceify/code/www/ > /dev/null 2>&1 || true
@@ -348,94 +339,91 @@ chmod 0755 /var/lib/spaceify/data/scripts/remove_images.sh > /dev/null 2>&1 || t
 # npm install -g n
 # n stable
 
+printf "\n\e[4mInstalling Node.js packages\e[0m\n\n"
+
 npm install -g node-gyp
 cd /var/lib/spaceify/code
 npm install
 
-# ----- Create and initialize Docker image ----- #
-image_reinstalled=0
-installed_version="/var/lib/spaceify/data/docker/installed_version"
+# ----- Docker image ----- #
+printf "\n\e[4mImporting the latestest spaceifyubuntu Docker image\e[0m\n"
 
-in=$(wget -qO- http://spaceify.org/downloads/image_version)									# Has the spaceify.org some version of the image available
-if [ -z "$in" ]; then in=0; fi
+installed_version_file="/var/lib/spaceify/data/docker/installed_version"
+installed_tar_file="/var/lib/spaceify/data/docker/spaceifyubuntu.tar"
+installed_tgz_file="/var/lib/spaceify/data/docker/spaceifyubuntu.tgz"
+installed_tar_gz_file="/var/lib/spaceify/data/docker/spaceifyubuntu.tar.gz"
 
-il=0																						# Has the local computer some version of the image build/imported
-if [ -s "$installed_version" ]; then il=$(< "$installed_version"); fi
+spaceify_version=$(wget -qO- http://spaceify.org/downloads/image_version)					# Is there a version of the image available in spaceify.org
+if [ -z "$spaceify_version" ]; then spaceify_version=0; fi
 
-ubun=$( echo $(docker images) | sed -n '/spaceifyubuntu/{p;q;}' )	# Is there really an build/imported image existing in the local computer
-[ -z "$ubun" ] && su=0 || su=1
+installed_version=0																			# Has the local computer some version of the image build/imported
+if [ -s $installed_version_file ]; then installed_version=$(< $installed_version_file); fi
 
-typeset -i in
-typeset -i il
+tgz_exists=0
+if [ -s $installed_tgz_file ]; then tgz_exists=1; fi
 
-if (($su == 0 && $il == 0 && $in == 0)) || (($su == 0 && $il != 0 && $in == 0)); then
-	# 1 --- Build : No existing image build/installed and image doesn't exist in spaceify.org
+typeset -i spaceify_version
+typeset -i installed_version
+typeset -i tgz_exists
+
+if (($installed_version == 0 && $spaceify_version == 0 && $tgz_exists == 0)); then
+	# Build and export : Existing Image is not available
+
 	cd /var/lib/spaceify/data/docker
 	printf "\nBuilding a new spaceifyubuntu Docker image...\n"
 	docker build --no-cache --rm -t spaceifyubuntu . > /dev/null 2>&1 || true
 
-	image_reinstalled=1
-elif (($su == 0 && $il == 0 && $in != 0)) || (($su == 0 && $il != 0 && $in != 0)) || (($su != 0 && $il == 0 && $in != 0)) || (($su != 0 && $il != 0 && $in != 0 && $il != $in)); then
-	# 2 ---Import : No existing image build/installed and image exists in spaceify.org
-	# 3 ---Import + clean : Image exists but versions can't be compared OR image exists and versions can be compared
+	ID=$(docker run -d spaceifyubuntu /bin/bash) > /dev/null 2>&1 || true
+	sudo docker export $ID > $installed_tar_file > /dev/null 2>&1 || true
+	gzip $installed_tar_file > /dev/null 2>&1 || true
+	mv $installed_tar_gz_file $installed_tgz_file > /dev/null 2>&1 || true
 
-	docker rmi spaceifyubuntu > /dev/null 2>&1 || true
+elif (($installed_version == $spaceify_version && $tgz_exists != 0)); then
+	# Import : Use existing spaceifyubuntu.tgz
+
+	printf "\nImporting existing spaceifyubuntu Docker image...\n"
+	cat $installed_tgz_file | sudo docker import - spaceifyubuntu > /dev/null
+
+else
+	# Load and import : spaceifyubuntu.tgz doesn't exit, the image must be loaded from spaceify.org
+
+	rm $installed_tgz_file > /dev/null 2>&1 || true
 
 	printf "\nDownloading the latest spaceifyubuntu Docker image...\n"
-	curl -o ~/spaceifyubuntu.tgz http://spaceify.org/downloads/spaceifyubuntu.tgz
+	curl -o $installed_tgz_file http://spaceify.org/downloads/spaceifyubuntu.tgz
 
-	if [ -s ~/spaceifyubuntu.tgz ]; then
+	if [ -s $installed_tgz_file ]; then
 		printf "\nImporting the spaceifyubuntu Docker image...\n"
-		cat ~/spaceifyubuntu.tgz | sudo docker import - spaceifyubuntu > /dev/null
-		rm ~/spaceifyubuntu.tgz > /dev/null 2>&1 || true
-
-		image_reinstalled=1
+		cat $installed_tgz_file | sudo docker import - spaceifyubuntu > /dev/null
 	fi
-elif (($su != 0 && $il == 0 && $in == 0)) || (($su != 0 && $il != 0 && $in == 0)); then
-	# 4 ---No operation : Image exists and spaceify.org doesn't have the image
-	:
+
 fi
 
 ubun=$( echo $(docker images) | sed -n '/spaceifyubuntu/{p;q;}' )
 if [ -z "$ubun" ]; then
-	. /var/lib/spaceify/data/scripts/cleanup_installation.sh "remove"
-	printf "\nAborting installation because the required spaceifyubuntu Docker image doesn't exist.\nRun 'apt-get --purge remove Spaceify' to remove incomplete installation.\n\n"
+	. /var/lib/spaceify/data/scripts/cleanup_installation.sh "purge"
+	printf "\nAborting installation because the required spaceifyubuntu Docker image doesn't exist.\nRun 'apt-get purge spaceify' to remove incomplete installation.\n\n"
 	exit 1
 else
-	printf "$in" > "$installed_version"														# Update the version file
+	printf "$spaceify_version" > $installed_version_file									# Update the version file
 fi
 
-# ----- Create user names and passwords for edge and admin ----- #
+# ----- Register edge to Spaceify - Create user name and password for edge when necessary ----- #
+printf "\n\e[4mRegistering this edge computer\e[0m\n"
 
-	# -- try to find previous registration (edge_id.uuid) -- #
-edge_uuid=""
-edge_password=""
-if [ -e /var/lib/spaceify/data/db/edge_id.uuid ]; then
-	edge_uuid=$(</var/lib/spaceify/data/db/edge_id.uuid)
-elif [ -e /tmp/edge_id.uuid ]; then
-	edge_uuid=$(</tmp/edge_id.uuid)
-fi
+edge_uuid=$(sqlite3 /var/lib/spaceify/data/db/spaceify.db "SELECT edge_id FROM user;")
+edge_password=$(sqlite3 /var/lib/spaceify/data/db/spaceify.db "SELECT edge_password FROM user;")
 
-	# -- parse file content if edge_id.uuid was found -- #	
-
-if [[ "$edge_uuid" != "" ]]; then
-	OIFS="$IFS"
-	IFS="," read -ra auuid <<< "$edge_uuid"
-	IFS="$OIFS"
-
-	edge_uuid="${auuid[0]}"
-	edge_password="${auuid[1]}"
-fi
-
-	# -- Try to register this edge computer only if it's not already registered -- #
 registration_result=""
-registration_attempt=1
+registration_attempt=0
 
 if [[ "$edge_uuid" == "" ]]; then
-	printf "\nTrying to register this edge computer to spaceify.net."
+	printf "\nExisting registration was not found. Creating a new edge id and trying to register it to spaceify.net.\n"
 
-	# try five times to register a new edge_id
-	while [ $registration_attempt -lt 6 ]; do
+	# Try five times to register a new edge_id
+	while [ $registration_attempt -lt 5 ]; do
+		let registration_attempt+=1
+
 		printf "\nAttempt ${registration_attempt} of 5\n"
 
 		data1=$(openssl rand -hex 4)
@@ -446,7 +434,7 @@ if [[ "$edge_uuid" == "" ]]; then
 		edge_uuid="${data1}-${data2}-${data3}-${data4i}-${data4r}"
 
 		edge_password=$(openssl rand -hex 16)
-																				# ToDo: https://spaceify.net/edge_register.php (see also config.js)
+																							# ToDo: https://spaceify.net/edge_register.php (see also config.js)
 		registration_result=$(curl -d "eid=${edge_uuid}&epw=${edge_password}" --location "http://spaceify.net/edge_register.php")
 		if [[ "$registration_result" == "" ]]; then
 			echo "${edge_uuid},${edge_password}" > /var/lib/spaceify/data/db/edge_id.uuid
@@ -454,20 +442,40 @@ if [[ "$edge_uuid" == "" ]]; then
 		else
 			printf "\nRegistration result: ${registration_result}\n"
 		fi
-
-		let registration_attempt=registration_attempt+1
 	done
 fi
 
 	# -- update the created/restored edge_id and password to the database -- #
-sqlite3 /var/lib/spaceify/data/db/spaceify.db "INSERT OR REPLACE INTO user (edge_id, edge_password)  VALUES('${edge_uuid}', '${edge_password}');"
+sqlite3 /var/lib/spaceify/data/db/spaceify.db "UPDATE user SET edge_id='$edge_uuid', edge_password='$edge_password';"
+
+	# -- Check/print registration status -- #
+if [ $registration_attempt -eq 5 ]; then
+
+	printf "\nRegistering this edge computer failed: ${registration_result}. The registration is required for some operations of the Spaceify core and it is highly recommended to finish the registration. Try to finish the registration manually by running command: spm register\n"
+
+elif [ $registration_attempt -gt 0 ] && [ $registration_attempt -lt 5 ]; then
+
+	printf "\nThis edge computer was registered successfully with the edge id ${edge_uuid}.\n"
+	printf "The registration file edge_id.uuid can be found from /var/lib/spaceify/data/db\n"
+	printf "Consider storing this file in a secure location for possible future use.\n"
+	printf "The registration file can be used to set or change registration when spaceify is installed or updated.\n"
+	pritnf "By placing the file to /tmp, before updating or installing, Spaceify uses it to register itself instead\n"
+	printf "of using its previous registration or creating a new registration.\n"
+	printf "Notice! Do not use the same registration on multiple edge computers.\n"
+
+else
+
+	printf "\nExisting registration file, containing edge id ${edge_uuid}, was found and is used to identify this edge computer.\n"
+
+fi
 
 # ----- Start services ----- #
+printf "\n\e[4mRestarting Spaceify's services and edge computers network\e[0m\n"
 
 #service udhcpd restart
 
 if [[ -z $(service network-manager status |& grep running) ]]; then
-	printf "\nNetworking is not restarted, please do it manually\n"
+	printf "\nNetworking is not restarted, please do it manually if necessary.\n"
 
 	resolvconf -u
 else
@@ -491,71 +499,14 @@ service spaceifyhttp restart > /dev/null 2>&1 || true
 
 service monit restart > /dev/null 2>&1 || true
 
-# ----- Install packages if new image was created ----- #
+# ------ Reinstall packages from Spaceifys previous installation ----- #
+. /var/lib/spaceify/data/scripts/install_packages.sh
 
-if [[ $image_reinstalled != 0 ]]; then
-
-	work_path="/tmp/docimg/"
-
-	packages=()																					# Get the installed application packages
-	FILES=/var/lib/spaceify/data/installed/*
-	for f in $FILES; do
-		if [[ "$f" != "/var/lib/spaceify/data/installed/*" ]] && [[ "$f" != "/var/lib/spaceify/data/installed/readme.txt" ]]; then
-			packages+=("$f")
-		fi
-	done
-	packages_count=${#packages[@]}
-
-	if [[ $packages_count != 0 ]]; then
-		printf "\n\nReinstalling existing applications because the spaceifyubuntu Docker image is changed.\n"
-		sleep 5
-
-		mkdir -p $work_path > /dev/null 2>&1 || true
-
-		for (( i=0; i<${packages_count}; i++ )); do
-			let app=i+1
-			str=""
-			printf "\n\e[4mReinstalling application ${app} of ${packages_count}\e[0m\n\n"
-
-			file=${packages[$i]##*/}
-			cp "${packages[$i]}" "$work_path"
-			spm install "$work_path$file"
-		done
-
-		rm -r $work_path > /dev/null 2>&1 || true
-	fi
-
-fi
-
-# ----- Information about the installation ----- #
-
-	# -- Check registration status -- #
-if [ $registration_attempt -eq 6 ]; then
-
-	printf "\n\nRegistering this edge computer failed: ${registration_result}. The registration is required for some operations of the Spaceify core and it is highly recommended to finish the registration. Try to finish the registration manually by running command: spm register\n\n"
-
-elif [ $registration_attempt -gt 1 ] && [ $registration_attempt -lt 6 ]; then
-
-	printf "\n\nThis edge computer was registered successfully with the edge id ${edge_uuid}.\n"
-	printf "The registration file edge_id.uuid can be found here: /var/lib/spaceify/data/db\n"
-	printf "Store this file in a secure location for future use.\n"
-	printf "If the file is placed to /tmp directory prior to reinstalling Spaceify the previous registration is used. Notice: do not use the same edge id in multiple edge computers.\n"
-	printf "When updating Spaceify the existing registration is used and no involvement from the users part is required.\n\n"
-
-else
-
-	printf "\n\nExisting registration file, containing edge id ${edge_uuid}, was found and is used to identify this edge computer.\n\n"
-
-fi
-
-	# -- Installed -- #
+# ----- Spaceify is now installed ----- #
 versions=$(< /var/lib/spaceify/versions)													# Get the current version string
 vs=$(echo $versions | awk -F : '{print $2}')
 
-printf "\n\nSpaceify version $vs is now installed.\n"
+printf "\n\e[4mSpaceify version $vs is now installed\e[0m\n\n"
 
 # Script is found here after installation, if testing is required (eg. finding where the script fails): /var/lib/dpkg/info/spaceify.postinst
 # After changing the script run dpkg-reconfigure spaceify
-
-
-
