version 0.1.6

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -160,13 +160,13 @@ sed -i "s/%1/${core_port}/" /etc/monit/conf.d/spaceify.conf
 #######################################
 lease=""																					# Get the leases for the user selected network adapter connected to the internet
 find="option domain-name-servers "
-if [[ -s "/var/lib/dhcp/dhclient.${eth}.leases" ]]; then									# Try different locations (FILE exists and has a size greater than zero)
+if [ -s "/var/lib/dhcp/dhclient.${eth}.leases" ]; then										# Try different locations (FILE exists and has a size greater than zero)
 	lease="/var/lib/dhcp/dhclient.${eth}.leases"
-elif [[ -s "/var/lib/dhcp/dhclient.leases" ]]; then
+elif [ -s /var/lib/dhcp/dhclient.leases ]; then
 	lease="/var/lib/dhcp/dhclient.leases"
-elif [[ -s "/var/lib/dhcp3/dhclient.${eth}.leases"  ]]; then
+elif [ -s "/var/lib/dhcp3/dhclient.${eth}.leases"  ]; then
 	lease="/var/lib/dhcp3/dhclient.${eth}.leases"
-elif [[ -s "/var/lib/dhcp3/dhclient.leases" ]]; then
+elif [ -s /var/lib/dhcp3/dhclient.leases ]; then
 	lease="/var/lib/dhcp3/dhclient.leases"
 else
 	find="nameserver"
@@ -275,48 +275,9 @@ cd /var/lib/spaceify/data/db
 
 dbs="/var/lib/spaceify/data/db/spaceify.db"
 
-if [ -e $dbs ]; then																		# database exists
-
-	#rows=$(sqlite3 $dbs -separator ";" "SELECT unique_name, unique_directory, docker_image_id, type, version FROM applications")
-	#splt=(${rows//$';'/ })
-	#
-	#iter=$((${#splt[@]} - 5))
-	#for i in $(seq 0 4 $iter); do
-	#
-	#	unique_name=${splt[$i]}
-	#	unique_directory=${splt[$(($i + 1))]}
-	#	docker_image_id=${splt[$(($i + 2))]}
-	#	type=${splt[$(($i + 3))]}
-	#	version=${splt[$(($i + 4))]}
-	#
-	#	$(sqlite3 $dbs "DELETE FROM applications WHERE unique_name='${unique_name}'")		# Delete database entries
-	#	$(sqlite3 $dbs "DELETE FROM provided_services WHERE unique_name='${unique_name}'")
-	#	$(sqlite3 $dbs "DELETE FROM inject_hostnames WHERE unique_name='${unique_name}'")
-	#	$(sqlite3 $dbs "DELETE FROM inject_files WHERE unique_name='${unique_name}'")
-	#
-	#	docker rmi $docker_image_id  > /dev/null 2>&1 || true								# Remove application images
-	#
-	#	directory=""																		# Remove applications files but leave persistent volume untouched
-	#	if [[ "$type" == "spacelet" ]]; then
-	#		directory="/var/lib/spaceify/data/spacelets/${unique_directory}volume/"
-	#	elif [[ "$type" == "sandboxed" ]]; then
-	#		directory="/var/lib/spaceify/data/sandboxed/${unique_directory}volume/"
-	#	elif [[ "$type" == "native" ]]; then
-	#		directory="/var/lib/spaceify/data/native/${unique_directory}volume/"	
-	#	fi
-	#
-	#	rm -r "${directory}application" > /dev/null 2>&1 || true
-	#	rm -r "${directory}tls" > /dev/null 2>&1 || true
-	#
-	#	# reinstall applications here with spm?
-	#
-	#done
-	:
-else																						# create a new database
-
+if [ ! -e $dbs ]; then																		# create a new database
 	touch $dbs
 	sqlite3 $dbs < /var/lib/spaceify/data/db/create.sql
-
 fi
 
 #  Set release name and version and data version
@@ -354,20 +315,84 @@ chmod 0755 /usr/bin/spm  > /dev/null 2>&1 || true											# Spaceify Packet Ma
 chmod 0755 /var/lib/spaceify/data/scripts/stop_containers.sh > /dev/null 2>&1 || true		# a script to stop and remove running containers
 
 #----- Create and initialize Docker image -----#
+work_path="/tmp/docimg/"
+installed_file="/var/lib/spaceify/data/docker/installed_version"
 
-#ubun=$( docker images )
-#ubun=$( echo "$ubun" | sed -n '/spaceifyubuntu/{p;q;}' )
-#if [[ "$ubun" == "" ]]; then																# create image always (# only if it is not in the images list)
+in=$(wget -qO- http://spaceify.org/downloads/image_version)									# Has the spaceify.org some version of the image available
+if [ -z "$in" ]; then in=0; fi
 
-	printf "\nCreating the Docker image\n\n"
+il=0																						# Has the local computer some version of the image build/imported
+if [ -s "$installed_file" ]; then il=$(< "$installed_file"); fi
+
+ubun=$( echo $(docker images) | sed -n '/spaceifyubuntu/{p;q;}' )							# Is there really an build/imported image existing in the local computer
+[ -z "$ubun" ] && su=0 || su=1
+
+typeset -i in
+typeset -i il
+
+packages=()																					# Get the installed application packages
+FILES=/var/lib/spaceify/data/installed/*
+for f in $FILES; do
+	if [[ "$f" != "/var/lib/spaceify/data/installed/*" ]]; then									# Only empty or non-existing directory returns the searched directory name (itself)
+		packages+=("$f")
+	fi
+done
+plen=${#packages[@]}
+
+reinst=0
+
+if (($su == 0 && $il == 0 && $in == 0)) || (($su == 0 && $il != 0 && $in == 0)); then
+	# 1 --- Build : No existing image build/installed and image doesn't exist in spaceify.org
+	cd /var/lib/spaceify/data/docker
+	printf "\nBuilding a new Docker image...\n"
+	docker build --no-cache --rm -t spaceifyubuntu . > /dev/null 2>&1 || true
+
+	reinst=1
+elif (($su == 0 && $il == 0 && $in != 0)) || (($su == 0 && $il != 0 && $in != 0)) || \
+	 (($su != 0 && $il == 0 && $in != 0)) || (($su != 0 && $il != 0 && $in != 0 && $il != $in)); then
+	# 2 ---Import : No existing image build/installed and image exists in spaceify.org
+	# 3 ---Import + clean : Image exists but versions can't be compared OR image exists and versions can be compared
 
 	docker rmi spaceifyubuntu > /dev/null 2>&1 || true
 
-	cd /var/lib/spaceify/data/docker
-	docker build --no-cache --rm -t spaceifyubuntu .
-#fi
+	printf "\nDownloading the latest Docker image...\n"
+	curl -o ~/spaceifyubuntu.tgz http://spaceify.org/downloads/spaceifyubuntu.tgz
 
-# Update node.js to the latest stable release and install the required node.js modules (versions are defined in package.json)
+	if [ -s ~/spaceifyubuntu.tgz ]; then
+		printf "\nImporting the Docker image...\n"
+		cat ~/spaceifyubuntu.tgz | sudo docker import - spaceifyubuntu > /dev/null
+		rm ~/spaceifyubuntu.tgz > /dev/null 2>&1 || true
+
+		reinst=1
+	fi
+elif (($su != 0 && $il == 0 && $in == 0)) || (($su != 0 && $il != 0 && $in == 0)); then
+	# 4 ---No operation : Image exists and spaceify.org doesn't have image
+	:
+fi
+
+ubun=$( echo $(docker images) | sed -n '/spaceifyubuntu/{p;q;}' )
+if [ -z "$ubun" ]; then
+	printf "\nAborting installation because the required spaceifyubuntu Docker image doesn't exist.\n"
+	exit 1
+else
+	if [[ $plen != 0 && $reinst != 0 ]]; then												# Reinstall applications if there were installed applications and a new image was created
+		printf "\nReinstalling existing applications...\n"
+
+		mkdir -p $work_path > /dev/null 2>&1 || true
+
+		for (( i=0; i<${plen}; i++ )); do
+			file=${packages[$i]##*/}
+			cp "${packages[$i]}" "$work_path"
+			spm install "$work_path$file"
+		done
+
+		rm -r $work_path > /dev/null 2>&1 || true
+	fi
+
+	printf "$in" > "$installed_file"
+fi
+
+#----- Update node.js to the latest stable release and install the required node.js modules (versions are defined in package.json) -----#
 # npm cache clear -f
 # npm install -g n
 # n stable
